name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  schedule:
    - cron:  '0 4 * * 6'  # Run every Saturday
concurrency:
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.mode }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {mode: stable,  os: ubuntu-latest}
          # have 'arm64', need 'x86_64') ??
          # - {mode: stable,  os: macOS-latest}
          # “A computer is like air conditioning – it becomes useless when you open Windows.” - Linus Torvalds
          # - {mode: stable,  os: windows-latest}
          - {mode: stable,  os: ubuntu-latest}
          - {mode: nightly, os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia stable
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
          arch: x64
        if: ${{ matrix.mode == 'stable' }}
      - name: Setup Julia nightly
        uses: julia-actions/setup-julia@v1
        with:
          version: nightly
          arch: x64
        if: ${{ matrix.mode == 'nightly' }}

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13
      - run: |
          make -C deps/ FC=${{ env.FC }} all

      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
